version: '3.3'

services:
  pg_denormalized:

    # https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
    #THIS MUST BE ADDED AT SERVICE LEVEL
    shm_size: 1gb

    build: services/pg_denormalized
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_denormalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 1286:5432

  pg_normalized_batch:
    
    #THIS MUST BE ADDED AT SERVICE LEVEL
    shm_size: 1gb 
    
    build: services/pg_normalized_batch
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_normalized_batch:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 3858:5432
